// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductCatalogService.Infrastructure.Persistence;

#nullable disable

namespace ProductCatalogService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductCatalogService.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            Description = "High-performance laptop.",
                            Name = "Laptop Pro",
                            Price = 1200.00m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Accessories",
                            Description = "Ergonomic wireless mouse.",
                            Name = "Wireless Mouse",
                            Price = 25.50m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 3,
                            Category = "Home Goods",
                            Description = "12-cup automatic coffee maker.",
                            Name = "Coffee Maker",
                            Price = 75.99m,
                            StockQuantity = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
